FROM alpine:latest

ENV NGINX_VERSION 1.13.8
ENV NGINX_RTMP_VERSION 1.2.1

EXPOSE 1935
EXPOSE 8080

# Install Dependencies.
RUN	apk add --update \
  gcc binutils-libs binutils build-base libgcc make pkgconf pkgconfig \
  openssl openssl-dev ca-certificates pcre \
  musl-dev libc-dev pcre-dev zlib-dev

# Get nginx source.
RUN cd /tmp && wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
  && tar zxf nginx-${NGINX_VERSION}.tar.gz \
  && rm nginx-${NGINX_VERSION}.tar.gz

# Get nginx-rtmp module.
RUN cd /tmp && wget https://github.com/arut/nginx-rtmp-module/archive/v${NGINX_RTMP_VERSION}.tar.gz \
  && tar zxf v${NGINX_RTMP_VERSION}.tar.gz && rm v${NGINX_RTMP_VERSION}.tar.gz

# Compile nginx with nginx-rtmp module.
RUN cd /tmp/nginx-${NGINX_VERSION} \
  && ./configure --add-module=/tmp/nginx-rtmp-module-${NGINX_RTMP_VERSION}
RUN cd /tmp/nginx-${NGINX_VERSION} && make && make install

# Cleanup.
RUN rm -rf /var/cache/* /tmp/*

ADD nginx.conf /usr/local/nginx/conf/nginx.conf
RUN mkdir -p /var/www/live

# Forward logs to Docker
RUN ln -sf /dev/stdout /usr/local/nginx/logs/access.log && \
    ln -sf /dev/stderr /usr/local/nginx/logs/error.log

CMD ["/usr/local/nginx/sbin/nginx", "-g", "daemon off;"]